### PR TITLE
Keyboard navigation enabled for resource % bars

### LINKED ISSUE #797: The visualization of Resource Accessed view is not keyboard accessible
## Expected behavior (A clear and concise description of what you expected to happen) : 

User should be able to navigate the Resource Accessed view using keyboard Tab key.

## Describe the bug (Tell us what happens instead of the expected behavior) :

Using Tab key, user is not able to get into the Resource Accessed visualization.

## Steps to Reproduce :
1. Open Resource Accessed view for a course 
2. Instead of mouse, use key board Tab key. 
3. One can navigate through the page title bar, week selection, resource title, etc. However, one cannot get into the main bar chart view area using Tab key.

### PR DESCRIPTION
**Pull request by chrisrrowland**
Closes #797 

When pressing the tab key you can now navigate down the list of resources

1. Resource Name 1 (Screen reader will read file name "Some File.pdf")
2. Resource Bar 1 (Screen reader will read "Some File.pdf has been accessed by 37% of students.")
3. Resource Name 2
4. Resource Bar 2
etc.

### CODE REVIEW

**Comment by jonespm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/ITS_Teaching_And_Learning/my-learning-analytics/pullRequest?prid=6276541&bid=20429623)

File: assets/src/components/d3/createResourceAccessChart.js [hunk 1]
```diff
@@ -170,6 +177,7 @@ function createResourceAccessChart ({ data, width, height, domElement }) {
 
     bar.enter()
       .append('rect')
+      .attr('tabindex', d => d.index * 10 + 1)
```
Comment (jonespm) [inline assets/src/components/d3/createResourceAccessChart.js:180]: Interesting idea. Did you try to just set this to 0 for all of the elements? 0 should just navigate in sequence.

Comment (chrisrrowland) [reply assets/src/components/d3/createResourceAccessChart.js:180]: I really can't remember if I did or not. I know without this it would simply tab down the file names.  Based on the way the elements were laid out I think it was going to tab through all the file names sequentially then all the bars, but I'm not sure if  I observed that or simply suspected it...

**Review by pushyamig — APPROVED** [review]
