### PR TITLE
Change `class` prop to `className` in `SelectCard` (#1494)

### LINKED ISSUE #1494: Console warning from `class` prop usage in `SelectCard`
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

### Expected behavior (A description of what you expected to happen) : 

There should be no Web console errors or warnings when using the UI.

### Describe the bug (Tell us what happens instead of the expected behavior) :

There is a warning about an invalid prop name of `class` (as opposed to `className`). I introduced this accidentally in PR #1475. The warning is suppressed in production, so there is no visible error there.

### Steps to Reproduce :
1. Launch MyLA from a course, check you're on the view/visualization page.
2. Check the Web console.

### PR DESCRIPTION
**Pull request by ssciolla**
This PR aims to resolve #1494.

### CODE REVIEW

File: assets/src/components/SelectCard.js [hunk 1]
```diff
@@ -159,7 +159,7 @@ const SelectCard = props => {
     const label = 'About ' + cardData.title
     if (cardData.helpUrl) {
       return (
-        <div class={classes.help}>
+        <div className={classes.help}>
```
Comment (ssciolla) [inline assets/src/components/SelectCard.js:162]: Oddly enough, even though there was a warning about an invalid DOM property, the classes were still being applied. Otherwise I don't think my solution from #1475 would have worked.

**Review by jonespm — APPROVED** [review]
I saw this error too but figured it was unrelated and didn't fix it. Thanks for addressing.
