### PR TITLE
Fix snackbar sidedrawer issue

### LINKED ISSUE #705: Snackbar in grade distribution is triggered when sidebar is opened
## Expected behavior: 
Snackbar should only display when `Show my grade` is clicked. 

## Describe the bug (Tell us what happens instead of the expected behavior) :
Snackbar is triggered when sidebar is opened/closed if the `Show my grade` is changed _before_ the sidebar is opened. 

## Steps to Reproduce :
1. Navigate to grade distribution.
2. Click `Show my grade`
3. Click sidebar (top left button)
4. Snackbar will open (but state will not change of the `Show my grade`).

### PR DESCRIPTION
**Pull request by justin0022**
Resolves #705 

The cause was subtle, caused by putting the `UserSettingSnackbar` component within the `buildGradeView` function. This means that every time GradeDistribution rerenders (including any time that the side drawer is opened), a _brand new_ instance of the  `UserSettingSnackbar` component is created, which causes the `useEffect` function within the component to lose track of state, making it render every single time instead of checking the dependency array. 

Took forever to debug 😂

### CODE REVIEW

File: assets/src/containers/GradeDistribution.js [hunk 1]
```diff
@@ -56,75 +61,87 @@ function GradeDistribution (props) {
...
-            {content}
+            {
+              gradeLoaded
+                ? <BuildGradeView />
+                : <Spinner />
+            }
+            <UserSettingSnackbar
+              saved={userSettingSaved}
+              response={userSettingResponse}
+            />
```
Comment (justin0022) [inline assets/src/containers/GradeDistribution.js]: Such a simple fix!

File: assets/src/containers/GradeDistribution.js [hunk 2]
```diff
@@ -31,7 +31,12 @@ const styles = theme => ({
 })
 
 function GradeDistribution (props) {
-  const { classes, disabled, courseId, user } = props
+  const {
```
Comment (jonespm) [inline assets/src/containers/GradeDistribution.js]: This change seems like inconsistent style with the other components and containers. Is there a reason this style is changed/preferred? I know doesn't like multiple imports on the same line but this project ignores the [E401](https://lintlyci.github.io/Flake8Rules/rules/E401.html) lint suggestion in the backend. ;) Most examples of destructuring seem to keep everything on one line (as long as the line is short) and appears slightly easier to read for me.

Comment (justin0022) [reply assets/src/containers/GradeDistribution.js]: Good point, I'm reverting it back.
