### PR TITLE
Reenable Scroll to current week

### LINKED ISSUE #1147: AssignmentV2 is not scrolling to current week
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

### Expected behavior (A description of what you expected to happen) : 
When a user launches new assignment redesign, the table should auto scroll to a current week ( that is being calculated and week is slight orangish color), the Scrolling feature is broken right now.
Screen Shot 2020-12-09 at 9 09 04 AM

The feature mostly useful when loading the view.

### PR DESCRIPTION
**Pull request by pushyamig**
Fixes #1147

### CODE REVIEW

File: assets/src/components/AssignmentTable.js [hunk 1]
```diff
@@ -230,69 +230,69 @@ function AssignmentTable (props) {
...
-            <Tooltip title='Clear filters' placement='bottom' enterDelay={500}>
-              <FormControl className={classes.formControl}>
-                <Button size='small' variant='contained' onClick={() => clearFilters()} disabled={filtersAreClear}><ClearIcon /></Button>
-              </FormControl>
-            </Tooltip>
-          </Grid>
+          </Tooltip>
         </Grid>
+      </Grid>
+      <RootRef rootRef={tableRef}>
```
Comment (pushyamig) [inline assets/src/components/AssignmentTable.js:295]: I just moved the `RootRef` at the top of `TableContainer`. All the above changes are formatting changes

**Review by chrisrrowland — APPROVED** [review]
