### PR TITLE
Fixes #1466 - Limit display to a configurable number of resources

### LINKED ISSUE #1466: Resources Accessed view times out and does not load the bar chart in some courses
### Expected behavior (A description of what you expected to happen) : 
Resources Accessed view loads a bar chart showing the percent of students who viewed resources during the selected timeframe.

### Describe the bug (Tell us what happens instead of the expected behavior) :
For certain courses, the view does not load the bar chart.  Developer tools shows a 504 gateway timeout.

### Steps to Reproduce :
1. Go to MyLA for course 556396
2. Click on Resources Accessed
3. The bar chart does not load and a 504 shows up in the developer tools 

### Additional context (Add any other context about the problem here) :
This is a large course with 400+ students in it.

### PR DESCRIPTION
**Pull request by jonespm**
Display this limit to the user

I've tested this locally, I need to test if the header works with CORS on the server.

I could have also added this metadata to the JSON but that seems like it would have been a little more work changing the format of the JSON and providing this in the header should work good. 

Okay I tested this out, looks like it works fine.

### CODE REVIEW

File: assets/src/containers/ResourcesAccessed.js [hunk 1]
```diff
@@ -178,11 +179,14 @@ function ResourcesAccessed (props) {
...
-      const dataURL = `/api/v1/courses/${courseId}/resource_access_within_week?week_num_start=${weekRange[0]}&week_num_end=${weekRange[1]}&grade=${resourceGradeFilter}&resource_type=${resourceTypeFilter}`
+      const dataURL = `/api/v1/courses/${courseId}/resource_access_within_week/?week_num_start=${weekRange[0]}&week_num_end=${weekRange[1]}&grade=${resourceGradeFilter}&resource_type=${resourceTypeFilter}`
       const fetchOptions = { method: 'get', ...defaultFetchOptions }
       fetch(dataURL, fetchOptions)
         .then(handleError)
-        .then(res => res.json())
+        .then((response) => {
+          setResourcesLimit(response.headers.get("Resources-Limit"))
+          return response.json()
+        })
```
Comment (ssciolla) [inline assets/src/containers/ResourcesAccessed.js:189]: The `resourcesLimit` is not likely to change between sessions (or maybe ever once set), so I'm thinking this value should be added to the MyLA globals context processors, processed in `globals.js`, and passed down the component tree as a `prop`. Then we don't need the extra React state and this header. What do you think?

File: assets/src/containers/ResourcesAccessed.js [hunk 2]
```diff
@@ -213,21 +217,29 @@ function ResourcesAccessed (props) {
...
-          aspectRatio={0.3}
-          minHeight={350}
-        />
+        <>
+          <div style={{ textAlign: 'center', verticalAlign: 'middle' }}>
+            {typeof resourcesLimit === 'undefined' ? <div>Displaying all available resources in this course</div> :
+              <div>Displaying top {resourcesLimit} most accessed resources in this course</div>
+            }
+          </div>
+
```
Comment (ssciolla) [inline assets/src/containers/ResourcesAccessed.js:233]: Nit-pick: We should probably get you set up to use `standard` linting. I think it would flag some of this.

File: assets/src/containers/ResourcesAccessed.js [hunk 3]
```diff
@@ -213,21 +217,29 @@ function ResourcesAccessed (props) {
...
-          weekRange={weekRange}
-          gradeSelection={resourceGradeFilter}
-          resourceType={resourceTypeFilter}
-          aspectRatio={0.3}
-          minHeight={350}
-        />
+        <>
+          <div style={{ textAlign: 'center', verticalAlign: 'middle' }}>
+            {typeof resourcesLimit === 'undefined' ? <div>Displaying all available resources in this course</div> :
+              <div>Displaying top {resourcesLimit} most accessed resources in this course</div>
```
Comment (ssciolla) [inline assets/src/containers/ResourcesAccessed.js:230]: I think text should go in a different tag than `div`. You could also make use of Material UI's `Typography`.

File: dashboard/settings.py [hunk 4]
```diff
@@ -449,7 +449,8 @@ def apply_env_overrides(env: Dict[str, Any], environ: os._Environ) -> Dict[str,
 
 CONSTANCE_CONFIG = {
     'SURVEY_URL': ('', 'Full URL to Qualtrics survey. If left blank no survey link will display.', str),
-    'SURVEY_TEXT': ('Take Survey', 'Custom text for Qualtrics survey link and title. If left blank will default to "Take Survey". Must also configure SURVEY_URL. For best mobile fit keep this text to under 6 words/30 characters.', str)
+    'SURVEY_TEXT': ('Take Survey', 'Custom text for Qualtrics survey link and title. If left blank will default to "Take Survey". Must also configure SURVEY_URL. For best mobile fit keep this text to under 6 words/30 characters.', str),
+    'RESOURCE_LIMIT': (100, 'Maximum number of resources shown in a course resource access.', int)
```
Comment (ssciolla) [inline dashboard/settings.py:453]:
```suggestion
    'RESOURCE_LIMIT': (100, 'Maximum number of resources shown in the Resources Accessed visualization.', int)
```

File: dashboard/views.py [hunk 5]
```diff
@@ -5,9 +5,11 @@
 from datetime import timedelta
 from json import JSONDecodeError
 
+from constance import config
 import jsonschema
 import numpy as np
 import pandas as pd
+
 from django.conf import settings
```
Comment (ssciolla) [inline dashboard/views.py:13]: Nit-pick: The new seems unnecessary. I don't remember if I set this pattern up or not, but I guess I'd stick with the separate alphabetical order for direct and `from` imports.

```suggestion
import jsonschema
import numpy as np
import pandas as pd
from constance import config
from django.conf import settings
```

File: dashboard/views.py [hunk 6]
```diff
@@ -429,10 +431,22 @@ def resource_access_within_week(request, course_id=0):
...
     output_df.drop(columns=['name', 'resource_id_type'], inplace=True)
 
     logger.debug(output_df.to_json(orient='records'))
-    return HttpResponse(output_df.to_json(orient='records'),content_type='application/json')
+    response = HttpResponse(output_df.to_json(orient='records'), content_type='application/json')
+
+    # Add in this header if needed to pass that we limited this to the frontend
+    if total_rows > config.RESOURCE_LIMIT:
+        response['Resources-Limit'] = config.RESOURCE_LIMIT
+        response['Access-Control-Expose-Headers'] = 'Resources-Limit'
```
Comment (ssciolla) [inline dashboard/views.py:447]: Is this standard practice for something like this? Maybe we need the state and other changes in the frontend then, rather than going with the `globals` approach. Let me know what you think.

**Review by ssciolla — COMMENTED** [review]
This looks like it will work. I'll test it next. Let's have a discussion about the `globals` versus header approach. Your choice may be correct, but I'd like to hear the rationale.

File: assets/src/containers/ResourcesAccessed.js [hunk 7]
```diff
@@ -213,21 +217,29 @@ function ResourcesAccessed (props) {
...
-          data={resourceData}
-          weekRange={weekRange}
-          gradeSelection={resourceGradeFilter}
-          resourceType={resourceTypeFilter}
-          aspectRatio={0.3}
-          minHeight={350}
-        />
+        <>
+          <div style={{ textAlign: 'center', verticalAlign: 'middle' }}>
+            {typeof resourcesLimit === 'undefined' ? <div>Displaying all available resources in this course</div> :
```
Comment (ssciolla) [inline assets/src/containers/ResourcesAccessed.js:229]: I think you can just check if `resourcesLimit === undefined`.

File: assets/src/containers/ResourcesAccessed.js (hunk 1 above)
Comment (jonespm) [reply assets/src/containers/ResourcesAccessed.js:189]: I started with globals, but the backend is limiting this per course and globals is for everything. Some courses may not be limited and others might. If someone was enrolled in multiple courses and we wanted to display the specific limit to the student and it was in globals we'd have to do some calculations in the frontend rather than just passing the data from the backend. 

For instance if we passed the limit of 100, the frontend would have to see if there were 100 results and print a message that it was limited, otherwise it would print the total results. So there'd be some logic there.

There's also a small chance say if someone viewed this page before the reload and then again after that there would be more there that wouldn't be updated in the globals. Or since this is set in the admin, an admin could change the limit and get this de-synced. I figured passing it from the backend each time eliminates all these edge cases. 

I think we could also use these headers in the future, and was somewhat inspired by the Canvas pagination headers for trying this out.

File: assets/src/containers/ResourcesAccessed.js [hunk 8]
```diff
@@ -178,11 +179,14 @@ function ResourcesAccessed (props) {
   useEffect(() => {
     // Fetch data once all the setting data is fetched
     if (dataControllerLoad === 2 && !(resourceTypeFilter.length === 0)) {
-      const dataURL = `/api/v1/courses/${courseId}/resource_access_within_week?week_num_start=${weekRange[0]}&week_num_end=${weekRange[1]}&grade=${resourceGradeFilter}&resource_type=${resourceTypeFilter}`
+      const dataURL = `/api/v1/courses/${courseId}/resource_access_within_week/?week_num_start=${weekRange[0]}&week_num_end=${weekRange[1]}&grade=${resourceGradeFilter}&resource_type=${resourceTypeFilter}`
```
[the remark this answers is not in the document]
Comment (jonespm) [reply assets/src/containers/ResourcesAccessed.js:182]: I noticed that when it called this URL without the / it was getting a 301 redirect. I thought that was causing a problem but probably not, just left it in there to avoid that redirect.

What you suggest looks like a better option.

File: assets/src/containers/ResourcesAccessed.js (hunk 2 above)
Comment (jonespm) [reply assets/src/containers/ResourcesAccessed.js:233]: I had the extension installed but I checked it and looks like it needed a migration because the one I had was deprecated? I figured it wasn't reporting any problems so I was good. Updating and restarting I see it notices some issues. I can resolve that.

File: assets/src/containers/ResourcesAccessed.js (hunk 3 above)
Comment (ssciolla) [reply assets/src/containers/ResourcesAccessed.js:230]: Screenshot 2023-03-09 at 11 24 33 AM

Looks okay. I'd consider adding a little margin on the bottom after the text. This may be handled for you if you use `Typography`, or you may have more utilities available to you.

File: assets/src/containers/ResourcesAccessed.js (hunk 2 above)
Comment (ssciolla) [reply assets/src/containers/ResourcesAccessed.js:233]: Yeah, I think the `standard` VSCode plugin changed.

File: assets/src/containers/ResourcesAccessed.js (hunk 1 above)
Comment (ssciolla) [reply assets/src/containers/ResourcesAccessed.js:189]: Okay, yeah, I thought of the edge cases you alluded to, but you are adding complexity in other ways. I'm okay with this approach if you are.

File: assets/src/containers/ResourcesAccessed.js (hunk 7 above)
Comment (jonespm) [reply assets/src/containers/ResourcesAccessed.js:229]: Sure I can see if this works. I was going off [Stack Overflow advice](https://stackoverflow.com/questions/4725603/variable-undefined-vs-typeof-variable-undefined) to always use typeof since that won't fail, but I didn't try without. The way this is set it will either be set to some value or not set so easy to test.

File: assets/src/containers/ResourcesAccessed.js [hunk 9]
```diff
@@ -67,6 +67,7 @@ function ResourcesAccessed (props) {
   // this is the filter setting last saved by the user
   const [userSavedFilterSetting, setUserSavedFilterSetting] = useState(resourceGradeFilter)
   const [resourceAccessData, setResourceAccessData] = useState('')
+  const [resourcesLimit, setResourcesLimit] = useState(0)
```
Comment (ssciolla) [inline assets/src/containers/ResourcesAccessed.js:70]: There may be a bug here, I'm looking into it. I think you meant for the initial state to be `undefined`.

File: assets/src/containers/ResourcesAccessed.js (hunk 7 above)
Comment (ssciolla) [reply assets/src/containers/ResourcesAccessed.js:229]: I alluded to this in https://github.com/tl-its-umich-edu/my-learning-analytics/pull/1488/files#r1131323094, I think it may never be showing the first option because there is a default in the backend. Somehow it's just always "Displaying top most accessed resources in this course"

Comment (ssciolla) [reply assets/src/containers/ResourcesAccessed.js:229]: Got it. `repsonse.headers.get('Resources-Limit')` is returning `null` if it doesn't exist. Thus it's not `undefined`, and `null` gets passed into the string interpolation where it's ignored.

Comment (ssciolla) [reply assets/src/containers/ResourcesAccessed.js:229]: Something like this could work where you're using the setter.
```
      fetch(dataURL, fetchOptions)
        .then(handleError)
        .then((response) => {
          if (response.headers.has('Resources-Limit')) {
            setResourcesLimit(response.headers.get('Resources-Limit'))
          }
          return response.json()
        })
```

File: assets/src/containers/ResourcesAccessed.js (hunk 9 above)
Comment (ssciolla) [reply assets/src/containers/ResourcesAccessed.js:70]: I do think this should be `undefined`, but I don't think it's the direct cause of the issue. See conversation elsewhere.

Comment (jonespm) [reply assets/src/containers/ResourcesAccessed.js:70]: That makes sense. Probably also using `null` could work out here for what I'm intending, just would have to check that.

File: assets/src/containers/ResourcesAccessed.js (hunk 3 above)
Comment (jonespm) [reply assets/src/containers/ResourcesAccessed.js:230]: I can ask at the meeting!

Comment (jonespm) [reply assets/src/containers/ResourcesAccessed.js]: Jennifer said it's better to leave both in there so there's no confusion when it doesn't appear. Marking as resolved.

File: assets/src/containers/ResourcesAccessed.js [hunk 10]
```diff
@@ -213,21 +227,30 @@ function ResourcesAccessed (props) {
...
-        <ResourceAccessChart
-          data={resourceData}
-          weekRange={weekRange}
-          gradeSelection={resourceGradeFilter}
-          resourceType={resourceTypeFilter}
-          aspectRatio={0.3}
-          minHeight={350}
-        />
+        <>
+          <Typography style={{ textAlign: 'center', verticalAlign: 'middle' }} gutterBottom>
```
Comment (ssciolla) [inline assets/src/containers/ResourcesAccessed.js:238]: `verticalAlign` may not be needed here, not sure.

File: assets/src/containers/ResourcesAccessed.js [hunk 11]
```diff
@@ -213,21 +227,30 @@ function ResourcesAccessed (props) {
...
+            {
+              resourcesLimit === undefined
+                ? 'Displaying all available resources in this course'
+                : `Displaying top ${resourcesLimit} most accessed resources in this course`
```
Comment (ssciolla) [inline assets/src/containers/ResourcesAccessed.js:242]: Ternary could be moved into the string to reduce duplication; "Displaying ... resources in this course" is repeated.

**Review by ssciolla — APPROVED** [review]
LGTM! Tested and seems to be working as intended.

File: assets/src/containers/ResourcesAccessed.js (hunk 11 above)
Comment (jonespm) [reply assets/src/containers/ResourcesAccessed.js:242]: Yeah interesting, looks like I could just use
`            {`Displaying ${resourcesLimit ?? 'all available'} resources in this course`}`

File: assets/src/containers/ResourcesAccessed.js (hunk 10 above)
Comment (jonespm) [reply assets/src/containers/ResourcesAccessed.js]: Yeah doesn't look like it is
