### PR TITLE
#1497 fix error message when all assignments are graded

### LINKED ISSUE #1497: Assignment Planning: Display the course goal as null when all assignments are graded and students have not set a goal
### Expected behavior (A description of what you expected to happen) : 
The Minimum Goal for the course should be null and not show an error when a student hasn't set a course and assignment goals, even when all assignments are submitted and graded.

### Describe the bug (Tell us what happens instead of the expected behavior) :
Prerequisites: 

- Student has submitted all assignments on the course
- All assignments have been graded
- Student has not set up a Minimum Goal for the course

In these circumstances, MyLA is displaying the message "Scores no longer match goal" in the My Minimum Goal field.  This field should be blank because the student hasn't set a goal.

### Screenshots/Video (If possible, add media to help explain your problem) :
image

--------------------
Test Plan:
https://docs.google.com/spreadsheets/d/1fOLY2byRBUZ1JzCFir6WiIPfrMPN2_-7oJKr5zhsiEM/edit#gid=0

### PR DESCRIPTION
**Pull request by pushyamig**
Fixes #1497 

Test Plan
https://docs.google.com/spreadsheets/d/1fOLY2byRBUZ1JzCFir6WiIPfrMPN2_-7oJKr5zhsiEM/edit#gid=0

### CODE REVIEW

File: assets/src/components/AssignmentGoalInput.js [hunk 1]
```diff
@@ -76,16 +76,14 @@ function AssignmentGoalInput (props) {
...
-        <Button
-          variant='contained'
-          className={classes.clearButton}
-          onClick={handleClearGoalGrades}
-          aria-label='clear'
-        >
-          Clear
-        </Button>
-      }
+      <Button
```
Comment (pushyamig) [inline assets/src/components/AssignmentGoalInput.js:79]: This is just a space change to fix the Squiggly line in Editor

**Comment by pushyamig** [comment]
@zqian This needs a review as well

**Review by zqian — APPROVED** [review]
Setup localhost with Canvas Beta. The PR passed all all test cases inside [the test plan](https://docs.google.com/spreadsheets/d/1fOLY2byRBUZ1JzCFir6WiIPfrMPN2_-7oJKr5zhsiEM/edit#gid=0).
