### PR TITLE
i-icon compress the text

### LINKED ISSUE #1123: On the home page, cards with the i-icon compress the text below the title
### Expected behavior (A description of what you expected to happen) : 
All title cards should have the i-icon to link to help documentation.  When the i-icon is added, it should not cause the title and background to expand so much that it compresses the text below the title.

### Describe the bug (Tell us what happens instead of the expected behavior) :
When the i-icon is added to the title, text below the visualization title gets compressed.

### Steps to Reproduce :
1.  Go to the homepage for a MyLA course
2. Compare the cards with an i-icon to the one without to see an example

### Screenshots/Video (If possible, add media to help explain your problem) :

MyLA_HomePageCardsWithIcons

### PR DESCRIPTION
**Pull request by chrisrrowland**
Closes #1123 

Just removes the default padding at the bottom of the element so the presence of the info icon doesn't expand it's enclosing element downward.

### CODE REVIEW

**Comment by chrisrrowland** [comment]
I finally created a PR that codacy didn't hate. 🥇

File: assets/src/components/SelectCard.js [hunk 1]
```diff
@@ -151,7 +154,7 @@ const SelectCard = props => {
   function getHelpLink (cardData) {
     if (cardData.helpUrl) {
       return (
-        <Typography gutterBottom variant='h5' component='h4' className={classes.title}>
+        <Typography gutterBottom variant='h5' component='h4' className={ `${classes.title} ${classes.titleIcon}`}>
```
Comment (pushyamig) [inline assets/src/components/SelectCard.js:157]: this can be written as `{classes. title + ' ' + classes. titleIcon} `

**Review by pushyamig — APPROVED** [review]
I did not run the change locally, but looks ok.
