### PR TITLE
fixes #1589: debounce and read snackbar for assignment planning

### LINKED ISSUE #1589: Snack bar fires visually whenever a value changes.
Snack bar fires visually whenever a value changes.  If I am using the arrow keys in any input[type="number"] it will fire with every increase.

Paradoxically the firings are not voiced by assistive tech (probably bc the snackbar is wrapped in a role="presentation") which is a good thing. Maybe fire onblur instead and voice it? Whatever - retain the role="presentation" if not planning to change how the snackbar fires - otherwise it would be too distracting for screen reader users.

### Steps to Reproduce :
1. Go to Assignment Planning
2. In Set Minimum Goal field, use the arrow key to raise or lower the goal grade.  The snack bar fires with each click.
3. Once a minimum goal is set, go to an assignment and use the arrow key to raise or lower the goal grade. The snack bar fires with each click. 

[MyLA Technical Review 7/24 - row 4](https://docs.google.com/spreadsheets/d/186xZEvxhbh55jLR_mRXT9tMrmFUlcBlUtkN5T7BuT64/edit?gid=886470260#gid=886470260)

### PR DESCRIPTION
**Pull request by jaydonkrooss**
Use the debounce package to delay opening the snackbar, also modify the snackbar component to alert screen readers instead of being hidden previously.

### CODE REVIEW

**Comment by pushyamig** [comment]
One usecase to test is the change of events like setting a Mini course goal, individual assignment goal, lock goal etc Is being logged in the backend with `eventlog_log`and only once. Since this change is GraphiQL mutation, so we want to make that is functional as well

I did not test this, but that is the important usecase to test.

File: assets/src/components/UserSettingSnackbar.js [hunk 1]
```diff
@@ -13,22 +14,27 @@ function UserSettingSnackbar (props) {
     saved,
     response,
     successMessage = 'Setting saved successfully!',
-    failureMessage = 'Setting not saved.'
+    failureMessage = 'Setting not saved.',
+    debounceAmount = 0
```
Comment (pushyamig) [inline assets/src/components/UserSettingSnackbar.js:18]: Can you add a comment the purpose of this variable?

File: assets/src/components/AssignmentGoalInput.js [hunk 2]
```diff
@@ -32,7 +32,7 @@ function AssignmentGoalInput (props) {
   } = props
 
   const [goalGradeInternal, setGoalGradeInternal] = useState(goalGrade)
-  const debouncedGoalGrade = useRef(debounce(q => setGoalGrade(q), 500)).current
+  const debouncedGoalGrade = useRef(debounce(q => setGoalGrade(q), 250)).current
```
Comment (pushyamig) [inline assets/src/components/AssignmentGoalInput.js:35]: Why was the number reduced?

File: assets/src/containers/AssignmentPlanningV2.js [hunk 3]
```diff
@@ -293,6 +293,7 @@ function AssignmentPlanningV2 (props) {
               <UserSettingSnackbar
                 saved={!mutationError && !mutationLoading && settingChanged}
                 response={{ default: 'success' }}
+                debounceAmount={750}
               />
```
Comment (pushyamig) [inline assets/src/containers/AssignmentPlanningV2.js:297]: This is milli second i suppose? why is this number chosen?

File: assets/src/components/AssignmentGoalInput.js (hunk 2 above)
Comment (jaydonkrooss) [reply assets/src/components/AssignmentGoalInput.js:35]: When I added a long debounce to the snackbar, the duration of this save would stack on top of the duration for the  snackbar pop up. It felt quite long compared to other inputs on the page, so I reduced this debounce amount. I didn't consider if there was any drawback to lowering this, other than the visualizations and input amounts rendering slightly faster

**Review by pushyamig — APPROVED** [review]
I have left minor comment for documenting. The Review is pre-approved by @gsilver  and I have tested i locally. I see the logging is working as expected

File: assets/src/containers/AssignmentPlanningV2.js (hunk 3 above)
Comment (jaydonkrooss) [reply assets/src/containers/AssignmentPlanningV2.js:297]: Not much thought went into it other than to add a buffer approximately around the duration of the other debounced input we had (originally 500ms). I ran it by @gsilver, and the 500-1000ms option seemed to be a good range. I'm also open to other guidance on this (and we can customize it later)

Comment (pushyamig) [reply assets/src/containers/AssignmentPlanningV2.js:297]: I think 750 seems fine, I just want to understand the reason.

File: assets/src/components/AssignmentGoalInput.js (hunk 2 above)
Comment (pushyamig) [reply assets/src/components/AssignmentGoalInput.js:35]: If it improve overall objective of the view that it is fine

**Comment by zqian** [comment]
To Pushyami's comment "One usecase to test is the change of events like setting a Mini course goal, individual assignment goal, lock goal etc Is being logged in the backend with eventlog_logand only once. Since this change GraphiQL mutation API, so we want to make that is functional as well"

I have verified the event log count is equal to the snack bar appearance. So if I updated the goal multiple times within the 750 ms, I see only one snack bar and only one new event log record.

File: assets/src/components/UserSettingSnackbar.js (hunk 1 above)
Comment (zqian) [reply assets/src/components/UserSettingSnackbar.js:18]: same question. Not sure why we need this debounceAmount param.

**Review by zqian — APPROVED** [review]
I have tested the PR on localhost. It passes the test cases. I left a minor comment.

File: assets/src/components/UserSettingSnackbar.js (hunk 1 above)
Comment (jaydonkrooss) [reply assets/src/components/UserSettingSnackbar.js]: I added a new comment to clarify in the new version of this file. There are other areas of the app that use this snackbar that we don't want to add a debounce to, at least for this issue. For instance, the grade filter setting for the resources accessed page triggers the snackbar. I've left it customizable for the future in case other pages would like a debounce
