### PR TITLE
Make asignment grade progress bar accessible

### LINKED ISSUE #799: Assignment "Percent of final grade" bar needs to be readable by screen reader software
## Expected behavior (A clear and concise description of what you expected to happen) : 

In Assignment Planning view, the Due by Date table is well constructed, but the SVG bar of "Percent of final grade" need to be readable by screen reader software

## Describe the bug (Tell us what happens instead of the expected behavior) :

Blind persona will not be able to read the score values of  the SVG bar of "Percent of final grade"

## Steps to Reproduce :

Either the SVG needs to be made readable (add score to the title element of the SVG and aria-labelledby attribute to the SVG pointing to the ID of the title) OR add a screen-reader-only span to the same cell with the score in it.
Note: some screen reader software may be able to parse the SVG and get the text. This is not a universal capability and above method is prefered

### PR DESCRIPTION
**Pull request by chrisrrowland**
Fixes #799 adds a property to ProgressBarV2 for descriptions.

AssignmentTable constructs and passes a description.

### CODE REVIEW

File: assets/src/components/AssignmentTable.js [hunk 1]
```diff
@@ -120,6 +120,16 @@ function AssignmentTable (props) {
     }
   }, [currentWeekRow.current])
 
+  const getDescription = (assignment) => {
```
Comment (justin0022) [inline assets/src/components/AssignmentTable.js:123]: I think it's worth using template literals here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals. You'll be able to avoid concat-ing using template literals

**Review by justin0022 — CHANGES_REQUESTED** [review]
One minor change, otherwise 👍

File: assets/src/components/AssignmentTable.js (hunk 1 above)
Comment (chrisrrowland) [reply assets/src/components/AssignmentTable.js:123]: Ok I'll take another shot, I wasn't able to figure out how to reference the variables for some reason, thanks.

Comment (justin0022) [reply assets/src/components/AssignmentTable.js:123]:
```js
`
   ${assignment.goalGrade}
`
```
```js
`
   ${assignment.grade ? assignment.grade : 'Not graded'}
`
```

Both of these should work!

Comment (chrisrrowland) [reply assets/src/components/AssignmentTable.js]: Thanks, I had forgotten the $ 🤦

**Review by justin0022 — APPROVED** [review]
👍

**Comment by jonespm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- assets/src/components/AssignmentTable.js  3
- assets/src/components/ProgressBarV2.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/ITS_Teaching_And_Learning/my-learning-analytics/pullRequest?prid=6393213&bid=20733691)
